project_id = "ynphvrkktapgghzxjakp"

[functions.send-email]
verify_jwt = true

[functions.send-templated-email]
verify_jwt = true

[functions.manage-user]
verify_jwt = true

[functions.seed-demo-data]
verify_jwt = true

[functions.create-consultant]
verify_jwt = false

[functions.grant-consultant]
verify_jwt = true

[functions.generate-policy-documents]
verify_jwt = true

[functions.retail-policy-lookup]
verify_jwt = true

[functions.grant-role]
verify_jwt = true

[functions.analyze-damage]
verify_jwt = true

[functions.analyze-device]
verify_jwt = true

[functions.analyze-receipt]
verify_jwt = true

[functions.seed-retail-data]
verify_jwt = false

[functions.service-agent]
verify_jwt = true

[functions.grant-system-admin]
verify_jwt = true

[functions.send-claim-document-request]
verify_jwt = false

[functions.get-claim-upload-details]
verify_jwt = false

[functions.upload-claim-document]
verify_jwt = false

[functions.process-claim-automatically]
verify_jwt = false

[functions.reanalyze-claim-documents]
verify_jwt = true

[functions.resend-communication]
verify_jwt = false

[functions.claims-fulfillment-advisor]
verify_jwt = true

[functions.regenerate-communications]
verify_jwt = true

